# Generated by Django 3.0.7 on 2021-03-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatWise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RaDEC', models.CharField(max_length=35)),
                ('RA', models.DecimalField(decimal_places=9, max_digits=15)),
                ('DEC', models.DecimalField(decimal_places=9, max_digits=15)),
                ('FoundInSearch', models.CharField(max_length=50)),
                ('AddDate', models.DateField(blank=True, null=True)),
                ('w1mpro', models.DecimalField(decimal_places=6, max_digits=11)),
                ('w1sigmpro', models.DecimalField(decimal_places=6, max_digits=11)),
                ('w1snr_pm', models.DecimalField(decimal_places=6, max_digits=11)),
                ('w2mpro', models.DecimalField(decimal_places=6, max_digits=11)),
                ('w2sigmpro', models.DecimalField(decimal_places=6, max_digits=11)),
                ('w2snr_pm', models.DecimalField(decimal_places=6, max_digits=11)),
                ('PMRA', models.DecimalField(decimal_places=6, max_digits=11)),
                ('sigPMRA', models.DecimalField(decimal_places=6, max_digits=11)),
                ('PMDec', models.DecimalField(decimal_places=6, max_digits=11)),
                ('sigPMDec', models.DecimalField(decimal_places=6, max_digits=11)),
                ('vtan', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('SIMBAD', models.BooleanField()),
                ('GaiaDR2plx', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('GaiaDR2PlxErr', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('BYW', models.CharField(blank=True, max_length=30, null=True)),
                ('GaiaCoMover', models.BooleanField(blank=True, null=True)),
                ('OnSpitzerPrg', models.CharField(blank=True, max_length=30, null=True)),
                ('W1W2Diff', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('W1W2DiffErr', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('TotalPM', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('TotalPMErr', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('H_W2', models.DecimalField(blank=True, decimal_places=6, max_digits=11)),
                ('JMag', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('JMagErr', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('JMagSrc', models.CharField(blank=True, max_length=30, null=True)),
                ('JW2Diff', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('JW2DiffErr', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('CatWISESpec', models.CharField(blank=True, max_length=30, null=True)),
                ('CatWISESpecSrc', models.CharField(blank=True, max_length=30, null=True)),
                ('SpizerConsider', models.BooleanField(blank=True, null=True)),
                ('WiseURL', models.URLField(blank=True)),
                ('Note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
