# Generated by Django 3.0.7 on 2021-03-23 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catwise',
            old_name='vtan',
            new_name='VTan',
        ),
    ]
