# Generated by Django 3.0.7 on 2021-03-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20210323_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catwise',
            name='H_W2',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='catwise',
            name='TotalPM',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='catwise',
            name='TotalPMErr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='catwise',
            name='W1W2DiffErr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True),
        ),
    ]
